config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates_presence_of :email
  validates :email, presence: true,
            format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create},
            uniqueness: {case_sensitive: false}

  has_many :contacttraces
end


class ContactTrace < ApplicationRecord
  belongs_to :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
    @contacttraces = ContactTrace.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.find_by_email(contact_params[:email])
 
    respond_to do |format|
      # TODO create db transaction https://stackoverflow.com/questions/2292815/save-an-active-records-array
      if !@contact.nil? and @contact.valid?
        save_contacttrace(@contact)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }      
      else
        @contact = Contact.new(contact_params)
        if @contact.save
          save_contacttrace(@contact)
          format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
          format.json { render :show, status: :created, location: @contact }
        else
          format.html { render :new }
          format.json { render json: @contact.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:email, :contacttrace)
    end
    def contacttrace_params
      params.require(:contacttrace).permit(contacttraces: [:url, :date_access])
    end

    def save_contacttrace(contact)
      params[:contacttrace].each do |item|
         cc = ContactTrace.new
         cc.url = item['url']
         cc.date_access = item['date_access']
         cc.contact = contact
        if !cc.save
          format.html { render :new }
          format.json { render json: cc.errors, status: :unprocessable_entity }
        end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contatos e seus acessos </h1>

<table>
 
  <thead>
    <tr>
      <th>Id</th>
      <th>Email</th>
      <th>URL acessada</th>
      <th>Data de acesso</th>
    </tr>
  </thead>


  <tbody>
    <% @contacttraces.each do |contacttrace| %>
      <tr>
        <td><%= contacttrace.contact.id %></td>
        <td><%= contacttrace.contact.email %></td>
        <td><%= contacttrace.url %></td>
        <td><%= contacttrace.date_access %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserTrackingCore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>